import {
    Send,
    Check,
    Visibility,
    Cancel,
    Home,
    BarChart,
    SmartToy,
    Group,
    Person,
    Settings,
    ArrowForward,
    ArrowDownward,
    CellTower,
    AddCircle,
    Description,
    FileUpload,
    FileDownload,
    Notifications,
    Search,
    FilterAlt,
    Phone,
    LocationOn,
    Edit,
    Delete,
    MoreVert,
    TrendingUp,
    TrendingDown,
    Public,
    ExpandMore,
    ExpandLess,
    Logout
} from '@mui/icons-material';

// SVG Icons Replaced with MUI Icons
export const Icons = {
    Send: (props) => <Send {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Check: (props) => <Check {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Eye: (props) => <Visibility {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    XCircle: (props) => <Cancel {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Home: (props) => <Home {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    BarChart: (props) => <BarChart {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Bot: (props) => <SmartToy {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Users: (props) => <Group {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    User: (props) => <Person {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Settings: (props) => <Settings {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    ArrowRight: (props) => <ArrowForward {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    ArrowDown: (props) => <ArrowDownward {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Broadcast: (props) => <CellTower {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    PlusCircle: (props) => <AddCircle {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    FileText: (props) => <Description {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Upload: (props) => <FileUpload {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Download: (props) => <FileDownload {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Bell: (props) => <Notifications {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Search: (props) => <Search {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Filter: (props) => <FilterAlt {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Phone: (props) => <Phone {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    MapPin: (props) => <LocationOn {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Edit: (props) => <Edit {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Trash: (props) => <Delete {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    MoreVertical: (props) => <MoreVert {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    TrendingUp: (props) => <TrendingUp {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    TrendingDown: (props) => <TrendingDown {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    Globe: (props) => <Public {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    ChevronDown: (props) => <ExpandMore {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    ChevronUp: (props) => <ExpandLess {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
    LogOut: (props) => <Logout {...props} fontSize={props.size ? "inherit" : "medium"} style={props.size ? { fontSize: props.size } : {}} />,
};
